"""add provider_job_id to transcripts

Revision ID: 7db147f65e7a
Revises: 87907852898c
Create Date: 2026-08-29 16:09:49.824518
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7db147f65e7a'
down_revision: str | None = '87907852898c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_job_id', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.drop_column('provider_job_id')

    # ### end Alembic commands ###
