"""add upload source to videos

Revision ID: 87907852898c
Revises: 809aa16e319c
Create Date: 2026-08-29 09:03:48.165498
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '87907852898c'
down_revision: str | None = '809aa16e319c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'source_type',
                sa.String(length=16),
                nullable=False,
                server_default='youtube',  # backfills existing rows
            )
        )
        batch_op.add_column(sa.Column('source_url', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('content_type', sa.String(length=100), nullable=True))
        batch_op.alter_column('youtube_video_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.alter_column('youtube_video_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('content_type')
        batch_op.drop_column('original_filename')
        batch_op.drop_column('source_url')
        batch_op.drop_column('source_type')

    # ### end Alembic commands ###
